---
- name: Create a directory if it does not exist
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Generate the configuration file
  shell: containerd config default > /etc/containerd/config.toml
  args:
    executable: /bin/bash

- name: Configure Systemd Cgroup
  shell: sed -i "s#SystemdCgroup\ \=\ false#SystemdCgroup\ \=\ true#g" /etc/containerd/config.toml
  args:
    executable: /bin/bash

- name: Template a file to /etc/file.conf
  template:
    src: crictl.yaml.j2
    dest: /etc/crictl.yaml

- name: Enable and start containerd
  systemd:
    name: containerd
    state: started
    enabled: yes

- name: Add crictl completion system wide
  shell: |
    source <(crictl completion bash)
    crictl completion bash > /etc/bash_completion.d/crictl
  args:
    executable: /bin/bash