---
- name: Install dependencies
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    state: latest
    update_cache: true

- name: Add Docker official signing GPG key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present

- name: Install container.d
  apt:
    name: containerd.io
    state: latest

- name: Downloading and extracting {{ crictl_app }} {{ crictl_version }} for Debian based distro
  unarchive:
    src: "{{ crictl_repo_url }}"
    dest: "{{ crictl_bin_path }}"
    owner: "{{ crictl_file_owner }}"
    group: "{{ crictl_file_group }}"
    extra_opts:
      - crictl
    remote_src: yes

- include_tasks: configure.yml 